<?php
define('PHPBB2DRUPAL_ACCESS', 'migrate phpbb forums');

/*
 * You must implement hook_migrate_api(), setting the API level to 2, for
 * your migration classes to be recognized by the Migrate module.
 */
function phpbb2drupal_migrate_api() {
  $api = array(
    'api' => 2,
  );
  return $api;
}

/**
 * Implements hook_permission().
 */
function phpbb2drupal_permission() {
  return array(
    PHPBB2DRUPAL_ACCESS => array(
      'title' => t('Migrate PHPBB forums into Drupal'),
    ),
  );
}

/**
 * Implements hook_menu().
 */
function phpbb2drupal_menu() {
  $items = array();

  $items['admin/content/phpbb'] = array(
    'title' => 'PHPBB migration',
    'type' => MENU_LOCAL_TASK | MENU_NORMAL_ITEM,
    'description' => 'Migrate PHPBB content into Drupal',
    'page callback' => 'phpbb2drupal_configure',
    'access arguments' => array(PHPBB2DRUPAL_ACCESS),
    'file' => 'phpbb2drupal.pages.inc',
    'weight' => 10,
  );

  return $items;
}
